const { readFileSync, writeFileSync, readdirSync } = require("node:fs");
const { join } = require("node:path");
const { createHash } = require("node:crypto");
function files(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? files(join(dir, entry.name)) : [join(dir, entry.name)]);
}
const assets = files(".next/static").filter(file => /\.(js|css|woff2?|png|svg)$/.test(file)).map(file => "/" + file.replaceAll("\\", "/").replace(".next/", "_next/"));
const version = createHash("sha256").update(readFileSync(".next/BUILD_ID")).update(readFileSync(".next/server/app/offline.html")).digest("hex").slice(0, 20);
const urls = ["/offline", "/manifest.webmanifest", "/pwa/icon-192.png", "/pwa/icon-512.png", "/pwa/apple-touch-icon.png", ...assets];
writeFileSync("public/sw.js", `// Generated by npm run build. UI only.\nconst VERSION = ${JSON.stringify(version)};\nconst ASSETS = ${JSON.stringify(urls)};\n` + readFileSync("src/features/pwa/worker.js", "utf8"));
console.log(`PWA: ${urls.length} UI files, version ${version}`);
